Hackathon/Hackathon.MVC/ViewModels/Warehouses/WarehouseViewModel.cs
using Hackathon.Application.DaliveryPoints;
using Hackathon.Application.Warehouses;
using System.Collections.Generic;

namespace Hackathon.MVC.ViewModels.Warehouses
{
    public class WarehouseViewModel : WarehouseDto
    {
        public IList<WarehouseDto> Warehouses { get; set; }

        public IList<DeliveryPointDto> DeliveryPoints { get; set; }
    }
}

Hackathon/Hackathon.MVC/Controllers/DeliveryPointsController.cs
using Hackathon.Application.Companies;
using Hackathon.Application.DaliveryPoints;
using Hackathon.Application.Users;
using Hackathon.Application.Warehouses;
using Hackathon.Domain.UserAggregate;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace Hackathon.MVC.Controllers
{
    [Authorize]
    public class DeliveryPointsController : Controller
    {
        private readonly ILogger<DeliveryPointsController> _logger;
        private readonly UserManager<User> _userManager;
        private readonly IUserService _userService;
        private readonly IWarehouseService _warehouseService;
        private readonly IDeliveryPointService _deliveryPointService;
        private readonly IAuthenticationSchemeProvider _schemeProvider;
        private readonly ICompanyService _companyService;

        public DeliveryPointsController(
            ILogger<DeliveryPointsController> logger,
            IAuthenticationSchemeProvider schemeProvider,
            UserManager<User> userManager,
            IUserService userService,
            IDeliveryPointService deliveryPointService,
            IWarehouseService warehouseService,
            ICompanyService companyService)
        {
            _logger = logger;
            _userManager = userManager;
            _userService = userService;
            _warehouseService = warehouseService;
            _deliveryPointService = deliveryPointService;
            _schemeProvider = schemeProvider;
            _companyService = companyService;
        }

        // GET: DeliveryPoints
        public async Task<IActionResult> Index()
        {
            return View(await _deliveryPointService.GetAllAsync());
        }

        // GET: DeliveryPoints/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var deliveryPoint = await _deliveryPointService.GetAsync((Guid) id);
            if (deliveryPoint == null)
            {
                return NotFound();
            }

            return View(deliveryPoint);
        }

        // GET: DeliveryPoints/Create
        public async Task<IActionResult> Create()
        {
            ViewData["WarehouseId"] = new SelectList(await _warehouseService.GetAllAsync(), "Id", "Name");
            return View();
        }

        // POST: DeliveryPoints/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,WarehouseId,Address,PhoneNumber,Id")]
            DeliveryPointDto deliveryPoint)
        {
            if (ModelState.IsValid)
            {
                deliveryPoint.Id = Guid.NewGuid();
                await _deliveryPointService.CreateAsync(deliveryPoint);
                return RedirectToAction(nameof(Index));
            }

            ViewData["WarehouseId"] = new SelectList(await _warehouseService.GetAllAsync(), "Id", "Name",
                deliveryPoint.WarehouseId);
            return View(deliveryPoint);
        }

        // GET: DeliveryPoints/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var deliveryPoint = await _deliveryPointService.GetAsync((Guid) id);
            if (deliveryPoint == null)
            {
                return NotFound();
            }

            ViewData["WarehouseId"] = new SelectList(await _warehouseService.GetAllAsync(), "Id", "Name",
                deliveryPoint.WarehouseId);
            return View(deliveryPoint);
        }

        // POST: DeliveryPoints/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Name,WarehouseId,Address,PhoneNumber,Id")]
            DeliveryPointDto deliveryPoint)
        {
            if (id != deliveryPoint.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _deliveryPointService.UpdateAsync(deliveryPoint);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!await DeliveryPointExists(deliveryPoint.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

                return RedirectToAction(nameof(Index));
            }

            ViewData["WarehouseId"] = new SelectList(await _warehouseService.GetAllAsync(), "Id", "Name",
                deliveryPoint.WarehouseId);
            return View(deliveryPoint);
        }

        // GET: DeliveryPoints/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var deliveryPoint = await _deliveryPointService.GetAsync((Guid) id);
            await _deliveryPointService.RemoveAsync(deliveryPoint.Id);

            return RedirectToAction(nameof(Index));
        }

        // POST: DeliveryPoints/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var deliveryPoint = await _deliveryPointService.GetAsync(id);
            return RedirectToAction(nameof(Index));
        }

        private async Task<bool> DeliveryPointExists(Guid id)
        {
            return (await _deliveryPointService.GetAllAsync()).Any(e => e.Id == id);
        }
    }
}

Hackathon/Hackathon.MVC/Controllers/WarehousesController.cs
using Hackathon.Application.Companies;
using Hackathon.Application.DaliveryPoints;
using Hackathon.Application.Users;
using Hackathon.Application.Warehouses;
using Hackathon.Domain.UserAggregate;
using Hackathon.MVC.ViewModels.Warehouses;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace Hackathon.MVC.Controllers
{
    [Authorize]
    public class WarehousesController : Controller
    {
        private readonly ILogger<WarehousesController> _logger;
        private readonly UserManager<User> _userManager;
        private readonly IUserService _userService;
        private readonly IWarehouseService _warehouseService;
        private readonly IDeliveryPointService _deliveryPointService;
        private readonly IAuthenticationSchemeProvider _schemeProvider;
        private readonly ICompanyService _companyService;

        public WarehousesController(
            ILogger<WarehousesController> logger,
            IAuthenticationSchemeProvider schemeProvider,
            UserManager<User> userManager,
            IUserService userService,
            IDeliveryPointService deliveryPointService,
            IWarehouseService warehouseService,
            ICompanyService companyService)
        {
            _logger = logger;
            _userManager = userManager;
            _userService = userService;
            _warehouseService = warehouseService;
            _deliveryPointService = deliveryPointService;
            _schemeProvider = schemeProvider;
            _companyService = companyService;
        }

        // GET: Warehouses
        public async Task<IActionResult> Index()
        {
            return View(await _warehouseService.GetAllAsync());
        }

        // GET: Warehouses/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var warehouse = await _warehouseService.GetAsync((Guid) id);
            var deliveryPoints = (await _deliveryPointService.GetAllAsync()).Where(x => x.WarehouseId == warehouse.Id)
                .ToList();

            var vm = new WarehouseViewModel()
            {
                DeliveryPoints = deliveryPoints
            };

            if (warehouse == null)
            {
                return NotFound();
            }

            return View(vm);
        }

        // GET: Warehouses/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Warehouses/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(WarehouseDto warehouse)
        {
            if (ModelState.IsValid)
            {
                warehouse.Id = Guid.NewGuid();

                var user = await _userManager.GetUserAsync(HttpContext.User);
                var company = await _companyService.GetAsync((Guid) user.CompanyId);
                warehouse.CompanyId = company.Id;


                await _warehouseService.CreateAsync(warehouse);
                return RedirectToAction(nameof(Index));
            }

            return View(warehouse);
        }

        // GET: Warehouses/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var warehouse = await _warehouseService.GetAsync((Guid) id);
            if (warehouse == null)
            {
                return NotFound();
            }

            return View(warehouse);
        }

        // POST: Warehouses/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("MinCode,MaxCode,Name,Address,PhoneNumber,Id")]
            WarehouseDto warehouse)
        {
            if (id != warehouse.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var user = await _userManager.GetUserAsync(HttpContext.User);
                    var company = await _companyService.GetAsync((Guid) user.CompanyId);
                    warehouse.CompanyId = company.Id;

                    await _warehouseService.UpdateAsync(warehouse);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!await WarehouseExists(warehouse.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

                return RedirectToAction(nameof(Index));
            }

            return View(warehouse);
        }

        // GET: Warehouses/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var warehouse = await _warehouseService.GetAsync((Guid) id);
            await _warehouseService.RemoveAsync(warehouse.Id);

            return RedirectToAction(nameof(Index));
        }

        // POST: Warehouses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            await _warehouseService.RemoveAsync(id);
            return RedirectToAction(nameof(Index));
        }

        private async Task<bool> WarehouseExists(Guid id)
        {
            var warehouse = await _warehouseService.GetAllAsync();
            return warehouse.Any(e => e.Id == id);
        }
    }
}

Hackathon/Hackathon.MVC/Views/Warehouses/Create.cshtml
@model Hackathon.Application.Warehouses.WarehouseDto

@{
    ViewData["Title"] = "Dodaj";
}

<div class="login-form">
    <form asp-action="Create" method="post">
        <div class="avatar">
            <i class="material-icons">home</i>
        </div>
        <h4 class="modal-title">Dodajanje skladišča</h4>
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <input type="text" asp-for="Name" class="form-control" placeholder="Naziv" required="required">
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="form-group">
            <input type="text" asp-for="MinCode" class="form-control" placeholder="Min. koda" required="required">
            <span asp-validation-for="MinCode" class="text-danger"></span>
        </div>
        <div class="form-group">
            <input type="text" asp-for="MaxCode" class="form-control" placeholder="Max. koda" required="required">
            <span asp-validation-for="MaxCode" class="text-danger"></span>
        </div>
        <div class="form-group">
            <input type="text" asp-for="Address" class="form-control" placeholder="Naslov" required="required">
            <span asp-validation-for="Address" class="text-danger"></span>
        </div>
        <div class="form-group">
            <input type="text" asp-for="PhoneNumber" class="form-control" placeholder="Tel. številka">
            <span asp-validation-for="PhoneNumber" class="text-danger"></span>
        </div>
        <input type="submit" class="btn btn-primary btn-block btn-lg" value="Dodaj">
    </form>
</div>

<div class="text-center">
    <a asp-action="Index">Nazaj na seznam skladišč</a>
</div>

@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

Hackathon/Hackathon.MVC/Views/Warehouses/Delete.cshtml
@model Hackathon.Application.Warehouses.WarehouseDto

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Warehouse</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MinCode)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MinCode)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MaxCode)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MaxCode)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Hackathon/Hackathon.MVC/Views/Warehouses/Details.cshtml
@model Hackathon.MVC.ViewModels.Warehouses.WarehouseViewModel

<div class="container">
    <div class="table-wrapper">
        <div class="table-title">
            <div class="row">
                <div class="col-sm-5">
                    <h2>Dostavne točke</h2>
                </div>
                <div class="col-sm-7">
                    <a asp-controller="DeliveryPoints" asp-action="Create" class="btn btn-primary">
                        <i class="material-icons">&#xE147;</i> <span>Dodaj dostavno točko</span>
                    </a>
                </div>
            </div>
        </div>
        <table class="table table-striped table-hover">
            <thead>
            <tr>
                <th>Naziv</th>
                <th>Naslov</th>
                <th>Skladišče</th>
                <th>Tel. številka</th>
                <th>Status</th>
                <th>Akcije</th>
            </tr>
            </thead>
            <tbody>
            @foreach (var deliveryPoint in Model.DeliveryPoints)
            {
                <tr>
                    <td>@Html.DisplayFor(modelItem => deliveryPoint.Name)</td>
                    <td>@Html.DisplayFor(modelItem => deliveryPoint.Address)</td>
                    <td>@Html.DisplayFor(modelItem => deliveryPoint.Warehouse.Name)</td>
                    <td>@Html.DisplayFor(modelItem => deliveryPoint.PhoneNumber)</td>
                    <td><span class="status text-success">&bull;</span> Obratuje</td>
                    <td>
                        <a asp-controller="DeliveryPoints" asp-action="Edit" asp-route-id="@deliveryPoint.Id" class="settings" title="Uredi" data-toggle="tooltip">
                            <i class="material-icons">&#xE8B8;</i>
                        </a>
                        <a asp-controller="DeliveryPoints" asp-action="Delete" asp-route-id="@deliveryPoint.Id" class="delete" title="Odstrani" data-toggle="tooltip">
                            <i class="material-icons">&#xE5C9;</i>
                        </a>
                    </td>
                </tr>
            }
            </tbody>
        </table>
        <div class="clearfix">
            <div class="hint-text">Prikazanih <b>@Model.DeliveryPoints.Count()</b> od <b>@Model.DeliveryPoints.Count()</b> zapisov.</div>
            <ul class="pagination">
                <li class="page-item disabled">
                    <a href="#">Nazaj</a>
                </li>
                <li class="page-item active">
                    <a href="#" class="page-link">1</a>
                </li>
                <li class="page-item">
                    <a href="#" class="page-link">2</a>
                </li>
                <li class="page-item">
                    <a href="#" class="page-link">3</a>
                </li>
                <li class="page-item">
                    <a href="#" class="page-link">4</a>
                </li>
                <li class="page-item">
                    <a href="#" class="page-link">5</a>
                </li>
                <li class="page-item">
                    <a href="#" class="page-link">Naprej</a>
                </li>
            </ul>
        </div>
    </div>
</div>

Hackathon/Hackathon.MVC/Views/Warehouses/Edit.cshtml
@model Hackathon.Application.Warehouses.WarehouseDto

@{
    ViewData["Title"] = "Edit";
}

<div class="login-form">
    <form asp-action="Edit">
        <div class="avatar"><i class="material-icons">home</i></div>
        <h4 class="modal-title">Urejanje skladišča</h4>
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>

        <div class="form-group">
            <input asp-for="MinCode" type="number" class="form-control" placeholder="Min koda" required/>
            <span asp-validation-for="MinCode" class="text-danger"></span>
        </div>
        <div class="form-group">
            <input asp-for="MaxCode" type="number" class="form-control" placeholder="Max koda" required/>
            <span asp-validation-for="MaxCode" class="text-danger"></span>
        </div>
        <div class="form-group">
            <input asp-for="Name" type="text" class="form-control" placeholder="Naziv" required/>
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="form-group">
            <input asp-for="Address" type="text" class="form-control" placeholder="Naslov" required/>
            <span asp-validation-for="Address" class="text-danger"></span>
        </div>
        <div class="form-group">
            <input asp-for="PhoneNumber" type="tel" class="form-control" placeholder="Tel. številka" />
            <span asp-validation-for="PhoneNumber" class="text-danger"></span>
        </div>
        <input type="hidden" asp-for="Id" />
        <input type="submit" class="btn btn-primary btn-block btn-lg" value="Shrani">
    </form>
</div>

<div class="text-center">
    <a asp-action="Index">Nazaj na seznam</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Hackathon/Hackathon.MVC/Views/Warehouses/Index.cshtml
@model IEnumerable<Hackathon.Application.Warehouses.WarehouseDto>

@{
    ViewData["Title"] = "Index";
}

<div class="container">
    <div class="table-wrapper">
        <div class="table-title">
            <div class="row">
                <div class="col-sm-5">
                    <h2>Skladišča</h2>
                </div>
                <div class="col-sm-7">
                    <a asp-action="Create" class="btn btn-primary">
                        <i class="material-icons">&#xE147;</i> <span>Dodaj skladišče</span>
                    </a>
                </div>
            </div>
        </div>
        <table class="table table-striped table-hover">
            <thead>
            <tr>
                <th>Naziv</th>
                <th>Naslov</th>
                <th>Razpon kode</th>
                <th>Status</th>
                <th>Akcije</th>
            </tr>
            </thead>
            <tbody>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>@Html.DisplayFor(modelItem => item.Address)</td>
                    <td>@Html.DisplayFor(modelItem => item.MinCode) - @Html.DisplayFor(modelItem => item.MaxCode)</td>
                    <td><span class="status text-success">&bull;</span> Obratuje</td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.Id" class="settings" title="Uredi" data-toggle="tooltip">
                            <i class="material-icons">&#xE8B8;</i>
                        </a>
                        <a asp-action="Delete" asp-route-id="@item.Id" class="delete" title="Izbriši" data-toggle="tooltip">
                            <i class="material-icons">&#xE5C9;</i>
                        </a>
                        <br />
                        <a asp-action="Details" asp-route-id="@item.Id" class="settings" title="Dostavne točke" data-toggle="tooltip">
                            <i class="material-icons">&#xea44;</i>
                        </a>
                    </td>
                </tr>
            }
            </tbody>
        </table>
        <div class="clearfix">
            <div class="hint-text">Prikazanih <b>@Model.Count()</b> od <b>@Model.Count()</b> zapisov.</div>
            <ul class="pagination">
                <li class="page-item disabled">
                    <a href="#">Nazaj</a>
                </li>
                <li class="page-item active">
                    <a href="#" class="page-link">1</a>
                </li>
                <li class="page-item">
                    <a href="#" class="page-link">2</a>
                </li>
                <li class="page-item">
                    <a href="#" class="page-link">3</a>
                </li>
                <li class="page-item">
                    <a href="#" class="page-link">4</a>
                </li>
                <li class="page-item">
                    <a href="#" class="page-link">5</a>
                </li>
                <li class="page-item">
                    <a href="#" class="page-link">Naprej</a>
                </li>
            </ul>
        </div>
    </div>
</div>