Hackathon/Hackathon.MVC/Controllers/DeliveriesController.cs
using Hackathon.Application.Companies;
using Hackathon.Application.DaliveryPoints;
using Hackathon.Application.Deliveries;
using Hackathon.Application.Warehouses;
using Hackathon.Domain.DeliveryAggregate;
using Hackathon.Domain.UserAggregate;
using Hackathon.MVC.ViewModels;
using Hackathon.MVC.ViewModels.Delivery;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Hackathon.MVC.Controllers
{
    [Authorize]
    public class DeliveriesController : Controller
    {
        private readonly UserManager<User> _userManager;
        private readonly IWarehouseService _warehouseService;
        private readonly IDeliveryService _deliveryService;
        private readonly IDeliveryPointService _deliveryPointService;
        private readonly ICompanyService _companyService;

        public DeliveriesController(
            UserManager<User> userManager,
            IWarehouseService warehouseService,
            IDeliveryService deliveryService,
            IDeliveryPointService deliveryPointService,
            ICompanyService companyService)
        {
            _userManager = userManager;
            _warehouseService = warehouseService;
            _deliveryService = deliveryService;
            _deliveryPointService = deliveryPointService;
            _companyService = companyService;
        }

        // GET: Deliveries
        public async Task<IActionResult> Index()
        {
            var user = await _userManager.GetUserAsync(HttpContext.User);
            var company = await _companyService.GetAsync((Guid) user.CompanyId);

            var vm = new DeliveryViewModel
            {
                DeliveriesInProgress = await _deliveryService.GetAllAsync(),
                DeliveriesRequests = await _deliveryService.GetAllAsync(),
                DestinationCompanies = company
            };

            return View(vm);
        }

        // GET: Deliveries/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var delivery = await _deliveryService.GetAsync((Guid) id);
            if (delivery == null)
            {
                return NotFound();
            }

            return View(delivery);
        }

        // GET: Deliveries/Create
        public async Task<IActionResult> Create()
        {
            ViewData["Companies"] = new SelectList(await _companyService.GetAllAsync(), "Id", "Name");
            return View();
        }

        // POST: Deliveries/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(DeliveryDto delivery)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var user = await _userManager.GetUserAsync(HttpContext.User);

                    var warehouse = (await _warehouseService.GetAllAsync())
                        .Any(x =>
                            x.CompanyId == delivery?.SourceCompanyId && x.MaxCode >= delivery?.Code &&
                            x.MinCode <= delivery.Code);

                    if (warehouse)
                    {
                        var newDelivery = new DeliveryDto()
                        {
                            Id = Guid.NewGuid(),
                            CreationTime = DateTime.Now,
                            DestinationCompanyId = user.CompanyId,
                            SourceCompanyId = delivery.SourceCompanyId,
                            Code = delivery.Code,
                            Status = DeliveryStatus.None
                        };

                        await _deliveryService.CreateAsync(newDelivery);
                        return RedirectToAction(nameof(Index));
                    }
                    else
                    {
                        ViewData["Companies"] = new SelectList(await _companyService.GetAllAsync(), "Id", "Name");
                        ModelState.AddModelError(string.Empty,
                            $"Nobeno skladišče, tega podjetja, ne sprejema distavne šifre {delivery.Code}");
                        return View(delivery);
                    }
                }
                catch (Exception e)
                {
                    ViewData["Companies"] = new SelectList(await _companyService.GetAllAsync(), "Id", "Name");
                    ModelState.AddModelError(string.Empty, "Podjetje s takšnim imenom ne obstaja. Navedite točno ime.");
                    return View(delivery);
                }
            }

            ViewData["Companies"] = new SelectList(await _companyService.GetAllAsync(), "Id", "Name");
            return View(delivery);
        }

        // GET: Deliveries/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var delivery = await _deliveryService.GetAsync((Guid) id);
            if (delivery == null)
            {
                return NotFound();
            }

            return View(delivery);
        }

        // POST: Deliveries/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, DeliveryDto delivery)
        {
            if (id != delivery.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var updateDelivery = await _deliveryService.GetAsync(id);

                    updateDelivery.DeliveryTime = delivery.DeliveryTime;
                    updateDelivery.DispatchTime = delivery.DispatchTime;
                    updateDelivery.DeliveryPointId = delivery.DeliveryPointId;

                    await _deliveryService.UpdateAsync(updateDelivery);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!await DeliveryExists(delivery.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

                return RedirectToAction(nameof(Index));
            }

            return View(delivery);
        }


        // GET: Deliveries/Delete/5
        public async Task<IActionResult> Dispatch(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var delivery = await _deliveryService.GetAsync((Guid) id);
            var company = await _companyService.GetAsync((Guid) delivery?.DestinationCompanyId);

            try
            {
                var (deliveryPoints, deliveryEvents) = await PrepareDeliveryData(delivery, company);

                return View(PrepareDispatchResponse(delivery, company, deliveryPoints, deliveryEvents));
            }
            catch (Exception e)
            {
                ModelState.AddModelError(
                    string.Empty,
                    "Prosimo vnesite skladišča (tudi min in max vrednost posebej) in dostavne točke, ter nato poskusite ponovno."
                );

                return View(
                    PrepareDispatchResponse(delivery, company, new List<DeliveryPointDto>(), new List<Event>())
                );
            }
        }

        private DeliveryViewModel PrepareDispatchResponse(
            DeliveryDto delivery,
            CompanyDto company,
            List<DeliveryPointDto> deliveryPoints,
            List<Event> deliveryEvents)
        {
            return new DeliveryViewModel()
            {
                Id = delivery.Id,
                Code = delivery.Code,
                DestinationCompanies = company,
                DeliveryPoints = deliveryPoints,
                DeliveryEvents = deliveryEvents
            };
        }

        private async Task<Tuple<List<DeliveryPointDto>, List<Event>>> PrepareDeliveryData(DeliveryDto delivery,
            CompanyDto company)
        {
            var warehouse = (await _warehouseService.GetAllAsync())
                .FirstOrDefault(x =>
                    x.CompanyId == company.Id && x.MaxCode >= delivery.Code && x.MinCode <= delivery.Code);

            var deliveryPoints = (await _deliveryPointService.GetAllAsync())
                .Where(x => x.WarehouseId == warehouse?.Id)
                .ToList();

            var deliveryEvents = PrepareDeliveryEvents(deliveryPoints);

            return new Tuple<List<DeliveryPointDto>, List<Event>>(deliveryPoints, deliveryEvents);
        }

        private List<Event> PrepareDeliveryEvents(List<DeliveryPointDto> deliveryPoints)
        {
            var deliveryEvents = new List<Event>();

            deliveryPoints.ForEach((x) =>
            {
                var deliveries = _deliveryService.GetAllAsync().GetAwaiter().GetResult()
                    .Where(o => o.DeliveryPointId == x.Id).ToList();

                deliveries.ForEach(d =>
                {
                    if (d.DispatchTime != null && d.DeliveryTime != null)
                    {
                        deliveryEvents.Add(new Event()
                        {
                            title = "Dostava",
                            start = d.DispatchTime,

Hackathon/Hackathon.MVC/Controllers/WarehousesController.cs
using Hackathon.Application.Companies;
using Hackathon.Application.DaliveryPoints;
using Hackathon.Application.Users;
using Hackathon.Application.Warehouses;
using Hackathon.Domain.UserAggregate;
using Hackathon.MVC.ViewModels.Warehouses;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace Hackathon.MVC.Controllers
{
    [Authorize]
    public class WarehousesController : Controller
    {
        private readonly ILogger<WarehousesController> _logger;
        private readonly UserManager<User> _userManager;
        private readonly IUserService _userService;
        private readonly IWarehouseService _warehouseService;
        private readonly IDeliveryPointService _deliveryPointService;
        private readonly IAuthenticationSchemeProvider _schemeProvider;
        private readonly ICompanyService _companyService;

        public WarehousesController(
            ILogger<WarehousesController> logger,
            IAuthenticationSchemeProvider schemeProvider,
            UserManager<User> userManager,
            IUserService userService,
            IDeliveryPointService deliveryPointService,
            IWarehouseService warehouseService,
            ICompanyService companyService)
        {
            _logger = logger;
            _userManager = userManager;
            _userService = userService;
            _warehouseService = warehouseService;
            _deliveryPointService = deliveryPointService;
            _schemeProvider = schemeProvider;
            _companyService = companyService;
        }

        // GET: Warehouses
        public async Task<IActionResult> Index()
        {
            return View(await _warehouseService.GetAllAsync());
        }

        // GET: Warehouses/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var warehouse = await _warehouseService.GetAsync((Guid) id);
            var deliveryPoints = (await _deliveryPointService.GetAllAsync()).Where(x => x.WarehouseId == warehouse.Id)
                .ToList();

            var vm = new WarehouseViewModel()
            {
                DeliveryPoints = deliveryPoints
            };

            if (warehouse == null)
            {
                return NotFound();
            }

            return View(vm);
        }

        // GET: Warehouses/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Warehouses/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(WarehouseDto warehouse)
        {
            if (ModelState.IsValid)
            {
                warehouse.Id = Guid.NewGuid();

                var user = await _userManager.GetUserAsync(HttpContext.User);
                var company = await _companyService.GetAsync((Guid) user.CompanyId);
                warehouse.CompanyId = company.Id;


                await _warehouseService.CreateAsync(warehouse);
                return RedirectToAction(nameof(Index));
            }

            return View(warehouse);
        }

        // GET: Warehouses/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var warehouse = await _warehouseService.GetAsync((Guid) id);
            if (warehouse == null)
            {
                return NotFound();
            }

            return View(warehouse);
        }

        // POST: Warehouses/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("MinCode,MaxCode,Name,Address,PhoneNumber,Id")]
            WarehouseDto warehouse)
        {
            if (id != warehouse.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var user = await _userManager.GetUserAsync(HttpContext.User);
                    var company = await _companyService.GetAsync((Guid) user.CompanyId);
                    warehouse.CompanyId = company.Id;

                    await _warehouseService.UpdateAsync(warehouse);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!await WarehouseExists(warehouse.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

                return RedirectToAction(nameof(Index));
            }

            return View(warehouse);
        }

        // GET: Warehouses/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var warehouse = await _warehouseService.GetAsync((Guid) id);
            await _warehouseService.RemoveAsync(warehouse.Id);

            return RedirectToAction(nameof(Index));
        }

        // POST: Warehouses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            await _warehouseService.RemoveAsync(id);
            return RedirectToAction(nameof(Index));
        }

        private async Task<bool> WarehouseExists(Guid id)
        {
            var warehouse = await _warehouseService.GetAllAsync();
            return warehouse.Any(e => e.Id == id);
        }
    }
}

Hackathon/Hackathon.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - WebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link href="https://fonts.googleapis.com/css?family=Roboto|Varela+Round" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@@fullcalendar/core@4.4.0/main.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@@fullcalendar/daygrid@4.4.0/main.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@@fullcalendar/timegrid@4.4.0/main.min.css">

    <script src="https://cdn.jsdelivr.net/npm/@@fullcalendar/core@4.4.0/main.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@@fullcalendar/daygrid@4.4.0/main.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@@fullcalendar/timegrid@4.4.0/main.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@@fullcalendar/interaction@4.4.0/main.min.js"></script>

    <link rel="stylesheet" href="~/css/site.css"/>

    <style type="text/css">
        body {
            color: #999;
            background: #f5f5f5;
            font-family: 'Varela Round', sans-serif;
        }

        .form-control {
            box-shadow: none;
            border-color: #ddd;
        }

        .form-control:focus { border-color: #00ab4e; }

        .dispatch-form-width {
            max-width: 700px;
            width: 700px !important;
        }

        .login-form {
            margin: 0 auto;
            padding: 30px 0;
            width: 350px;
        }

        .login-form form {
            color: #434343;
            border-radius: 1px;
            margin-bottom: 15px;
            background: #fff;
            border: 1px solid #f3f3f3;
            box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
            padding: 30px;
        }

        .login-form h4 {
            text-align: center;
            font-size: 22px;
            margin-bottom: 20px;
        }

        .login-form .avatar {
            color: #fff;
            margin: 0 auto 30px;
            text-align: center;
            width: 100px;
            height: 100px;
            border-radius: 50%;
            z-index: 9;
            background: #00ab4e;
            padding: 15px;
            box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.1);
        }

        .login-form .avatar i { font-size: 62px; }

        .login-form .form-group { margin-bottom: 20px; }

        .login-form .form-control, .login-form .btn {
            min-height: 40px;
            border-radius: 2px;
            transition: all 0.5s;
        }

        .login-form .close {
            position: absolute;
            top: 15px;
            right: 15px;
        }

        .login-form .btn {
            background: #00ab4e;
            border: none;
            line-height: normal;
        }

        .login-form .btn:hover, .login-form .btn:focus { background: #42ae68; }

        .login-form .checkbox-inline { float: left; }

        .login-form input[type="checkbox"] { margin-top: 2px; }

        .login-form .forgot-link { float: right; }

        .login-form .small { font-size: 13px; }

        .login-form a { color: #00ab4e; }

        .table-wrapper {
            background: #fff;
            padding: 20px 25px;
            margin: 30px 0;
            border-radius: 3px;
            box-shadow: 0 1px 1px rgba(0, 0, 0, .05);
        }

        .table-title {
            padding-bottom: 15px;
            background: #00ab4e;
            color: #fff;
            padding: 16px 30px;
            margin: -20px -25px 10px;
            border-radius: 3px 3px 0 0;
        }

        .table-title h2 {
            margin: 5px 0 0;
            font-size: 24px;
        }

        .table-title .btn {
            color: #566787;
            float: right;
            font-size: 13px;
            background: #fff;
            border: none;
            min-width: 50px;
            border-radius: 2px;
            border: none;
            outline: none !important;
            margin-left: 10px;
        }

        .table-title .btn:hover, .table-title .btn:focus {
            color: #566787;
            background: #f2f2f2;
        }

        .table-title .btn i {
            float: left;
            font-size: 21px;
            margin-right: 5px;
        }

        .table-title .btn span {
            float: left;
            margin-top: 2px;
        }

        table.table tr th, table.table tr td {
            border-color: #e9e9e9;
            padding: 12px 15px;
            vertical-align: middle;
        }

        table.table tr th:first-child { width: 60px; }

        table.table tr th:last-child { width: 100px; }

        table.table-striped tbody tr:nth-of-type(odd) { background-color: #fcfcfc; }

        table.table-striped.table-hover tbody tr:hover { background: #f5f5f5; }

        table.table th i {
            font-size: 13px;
            margin: 0 5px;
            cursor: pointer;
        }

        table.table td:last-child i {
            opacity: 0.9;
            font-size: 22px;
            margin: 0 5px;
        }

        table.table td a {
            font-weight: bold;
            color: #566787;
            display: inline-block;
            text-decoration: none;
        }

        table.table td a:hover { color: #00ab4e; }

        table.table td a.settings { color: #5c5a55; }

        table.table td a.delete { color: #F44336; }

        table.table td i { font-size: 19px; }

        table.table .avatar {
            border-radius: 50%;
            vertical-align: middle;
            margin-right: 10px;
        }

        .status {
            font-size: 30px;
            margin: 2px 2px 0 0;
            display: inline-block;
            vertical-align: middle;
            line-height: 10px;
        }

        .text-success { color: #10c469; }

        .text-info { color: #62c9e8; }

        .text-warning { color: #FFC107; }

        .text-danger { color: #ff5b5b; }

        .pagination {
            float: right;
            margin: 0 0 5px;
        }

        .pagination li a {
            border: none;
            font-size: 13px;
            min-width: 30px;
            min-height: 30px;
            color: #999;
            margin: 0 2px;
            line-height: 30px;
            border-radius: 2px !important;
            text-align: center;
            padding: 0 6px;
        }

        .pagination li a:hover { color: #666; }

        .pagination li.active a, .pagination li.active a.page-link { background: #00ab4e; }

        .pagination li.active a:hover { background: #0397d6; }

        .pagination li.disabled i { color: #ccc; }

        .pagination li i {
            font-size: 16px;
            padding-top: 6px
        }

        .hint-text {
            float: left;
            margin-top: 10px;
            font-size: 13px;
        }

        input::-webkit-outer-spin-button,
        input::-webkit-inner-spin-button {
            -webkit-appearance: none;
            margin: 0;
        }

        input[type=number] { -moz-appearance: textfield; }
    </style>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebApp</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Deliveries" asp-action="Index">Dostave</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Warehouses" asp-action="Index">Skladišča</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="DeliveryPoints" asp-action="Index">Dostavne točke</a>
                    </li>
                </ul>
                <div class="d-flex justify-content-end my-2 my-lg-0">
                    <partial name="_LoginPartial"/>
                </div>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2020 - WebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@RenderSection("Scripts", required: false)
</body>
</html>